### ISSUE TITLE
Bookmark Offer

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#15]
# Value Proposition

**As a** User ...(user, Author, logged in User...)
**I need** to have a bookmark function 
**to be able to** add the offer to a seperate bookmark page. 

# Description

![Image](https://user-images.githubusercontent.com/101577162/170996966-bd291239-7ffc-4702-bfb7-e5e1cc3c9a06.png)

![Image](https://user-images.githubusercontent.com/101577162/170996979-40b8ee72-a0d7-41b3-8bf1-0a775e820b2a.png)

# Acceptance Criteria

- [ ] If you click the "reservieren" Button the offer is added to the bookmark page and the reserved offer is marked as "is reserved".
- [ ] If you click the Button again, the offer is removed from the bookmark page and the "ist reserviert" marker is gone. 
- [ ] All bookmarked offers are shown on the bookmark page. 

# Tasks

(for developers team)

- [ ] Create the bookmark page
- [ ] Add an onClick event to the button to add and remove the offer from the bookmark page
- [ ] Check accessibility
- [ ] Add styled-components

# Complexity

M
