### ISSUE TITLE
add navbar

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#24]
# Value Proposition

**As a** User 
**I need** to have seperate pages and a footer with clickable icons 
**to be able to** have a better overview in the app. 

# Description

Scribble / design or text

# Acceptance Criteria

- [ ] The Form, Bookmarks, Insert and the map are on seperate pages. 
- [ ] Inside the footer is a navbar with five icons 
- [ ] When you click an icon, you are direted to the page and the color of the icon changes.

# Tasks

(for developers team)

- [ ] Add a footer component 
- [ ] add component to the app 
- [ ] Split the existing pages in to five 
- [ ] add the five icons and link them to the associated pages 
- [ ] Check on mobile Phone 

# Complexity
M
