### ISSUE TITLE
Offer Card (Menu)

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#3]

**Comment by tombein** [comment]
# Value Proposition

**As a** User 
**I need** to display the offer card. 
**to be able to** to read the offer from other people. 

# Description
<img width="429" alt="Bildschirmfoto 2022-05-11 um 11 42 15" src="https://user-images.githubusercontent.com/101577162/167820169-5a93b0cc-7be2-43d9-afcd-a9a3834e28b0.png">



# Acceptance Criteria

- [ ] A border box with round corners is displayed and the offer title as a headline
- [ ] A Text "Pfandflaschen im Wert von" is displayed 
- [ ] After that The value of the Deposit bottles is displayed
- [ ] The address of the offer location is displayed.
- [ ] A Text "Abholung zwischen" is displayed. 
- [ ] The Timeline of the offer is displayed. 


# Tasks

(for developers team)

- [ ] Create a new branch "offer-card" 
- [ ] Create a new component to render the offer card in a `<section>` Tag 
- [ ] Create a headline within a `<h2>` tag. The headline receives the title of the offer. 
- [ ] Create a textfield for the address informations within a `<p>` tag. 
- [ ] Create a bookmark button called "Reservieren". 
- [ ] Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered

# Complexity
L

**Comment by mbosselmann** [comment]
Hi Tom,
good job! 👍  I have some remarks:

To add `User Story` to this issue is not necessary, but if, it may be more reasonable to add it to the title of your user story to have a quick overview in your kanban board which issues are user stories and which are not (if you also add other issues to your board like tasks). But this is just an idea. ;)

In your **value proposition** you wrote `to be able to separate my offer from others and have an optimal view.` but if I understand your user story correctly only one offer will be rendered after implementing the functionality or? If this is true, then the outcome of your user story doesn't match the reason why the feature is needed. As the idea of your overall user story is very good I would suggest you to add another reason to your value proposition that makes more sense. :)

Regarding your `Reservieren` button: I think the `Reservieren` button is an element that should be implemented later when you want to implement the functionality. The reason for my suggestion is that now the user cannot do anything with this button for now, but would expect that something will happen after clicking this button. 😅

That's all for now. Feel free to ask me if you have further questions regarding my remarks. :)
