### ISSUE TITLE
See the details for the offer

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#5]

**Comment by tombein** [comment]
# Value Proposition

**As a** User
**I need** to have detailed information about the offer itself on a separate page with a picture.
**to be able to** have a better overview.

# Description

<img width="657" alt="Bildschirmfoto 2022-05-11 um 14 50 36" src="https://user-images.githubusercontent.com/101577162/167853894-cb37d731-8459-4c33-8129-e51b1dca45f6.png">


# Acceptance Criteria

- [ ] By clicking on the button (Info) on the offer, the missing information is shown up as an overlay.
- [ ] By clicking on the button on the detail page (cross) the list of entries should appear.


# Tasks

(for developers team)

- [ ] Create the button (info)
- [ ] Create the data structure to hold the entry details
- [ ] Render the data in the existing component
- [ ] Create the button (cross)
- [ ] Update the props
- [ ]  Apply basic styling (to distinguish between headlines and dynamic values)
- [ ] Add component to the app
- [ ] Add test to check if data is rendered


# Complexity
L

**Comment by julialoeschel** [comment]
Hey Tom, 
I have some thought on this : 

in VP: "I need to have detailed information about **What is the information  need?*"*
- will the detail page toggle? or is it a new page with routing? or do you create an overlay? please give more information about the feature here. 
- Your Task section on the other hand is quiet detailed. Usually you are not planning it out this detailed, but if it helps you to get started, go for it.

**Comment by julialoeschel** [comment]
👍
