### ISSUE TITLE
List entries

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#6]

**Comment by tombein** [comment]
User Story 

# Value Proposition

**As a** User 
**I need** to see all existing posts
**to be able to** to get a better overview of the information. 

# Description

![Bildschirmfoto 2022-05-11 um 14 42 04](https://user-images.githubusercontent.com/101577162/167856734-b082aa21-a8a7-4df2-8996-30dc6da2e451.png)


# Acceptance Criteria

- [ ] Each product should be visually separated
- [ ] Each product should be displayed with the important details
- [ ] All entries should be displayed

# Tasks

(for developers team)

- [ ] Create a data structure to hold an array of multiple entries
- [ ] Create a component to render the list of entries
- [ ] The component receives the array via props
- [ ] Add a test to check if all given entries are rendered
- [ ] Add component to the app

# Complexity
S

**Comment by cintiavazquez** [comment]
Hi Tom, I think your User Story is good, but it doesn't really match the value proposition. You wrote "As a User, I need to create a new post". In that case I would expect a form where you create a new post, but I think what you really mean here is "As a user I need to see all existing posts". Then the value proposition would match the criteria and tasks you defined.
