### ISSUE TITLE
Bookmark Offer

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#8]
# Value Proposition

**As a** User 
**I need** to make a reservation to show this offer is gone and
**to be able to** find reserved offers more easily in a single place.

# Description

![Image](https://user-images.githubusercontent.com/101577162/170996966-bd291239-7ffc-4702-bfb7-e5e1cc3c9a06.png)

![Image](https://user-images.githubusercontent.com/101577162/170996979-40b8ee72-a0d7-41b3-8bf1-0a775e820b2a.png)

# Acceptance Criteria

- [ ] If you click the "reservieren" Button the offer is added to the "Reservierungen page" and the reserved offer is marked as "is reserved".
- [ ] If you click the Button again, the offer is removed from the "Reservierungen page" and the "ist reserviert" marker is gone. 
- [ ] All "reserviert" offers are shown on the "Reservierungen page". 

# Tasks

(for developers team)

- [ ] Create the bookmark page
- [ ] Add an onClick event to the button to add and remove the offer from the "Reservierungen page"
- [ ] Check accessibility
- [ ] Add styled-components

# Complexity

M

**Comment by alexclaes** [comment]
Hi Tom, good user story!

You should work on a more consistent naming convention for the user. “Bookmarks” might be called “Reservierungen”. Right know it might be very confusing.

Please think about the value proposition. What is really the user’s need?  I think the user needs to make a reservation to a) show this offer is gone and  b) find reserved offers more easily in a single place.

**Comment by alexclaes** [comment]
👍
