### ISSUE TITLE
Create an Offer

### ISSUE THREAD

**Issue by tombein** [tombein/capstone-project#9]
# Value Proposition

**As a** User 
**I need** to add a new offer to my list
**to be able to** add a new offer-post to the list. 

# Description

![Bildschirmfoto 2022-05-16 um 14 15 13](https://user-images.githubusercontent.com/101577162/168590331-d264c7a0-3b30-4324-8866-4d99ad9f4c35.png)

# Acceptance Criteria

- [ ] An input field for the name is displayed, labeled "Title Angebot", 2-60 characters
- [ ] An input field for the address is displayed, labeled "Adresse", 2-60 characters 
- [ ] An input field the the date is displayed, labeled "Datum" where you can choose the date
- [ ] An input field for the time is displayed, labeled "Zeitraum" where you can choose a timeline
- [ ] An Input field is displayed, labeled "Anzahl bottles", where you can see how much your offer is worth 
- [ ] An Input field is displayed, labeled "Foto Abstellort", for a picture to see the location from the offer. 
- [ ] An input field is displayed, labeled "Notiz", to put some more detailed informations in.
- [ ] A Button is displayed, labeled "Inserieren", to post and save the offer. 
- [ ] After posting and save the offer, it will appear in the list of all offers. #6 
- [ ] After Saving the input fields are cleared. 

# Tasks

(for developers team)

- [ ] Create a new branch 
- [ ] Create an component to render the form 
- [ ] Add Text length validation (for fields "Title Angebot" and "Adresse")
- [ ] Add a test to check if all given entries are rendered
- [ ] Add component to the app
- [ ] Add test to check if data is rendered
- [ ] Check on mobile phone
- [ ] Check accessibility 

# Complexity

XL
